name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소에서 코드 가져오기
      uses: actions/checkout@v4
      
    - name: Node.js 20 환경 설정하기
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: 패키지(모듈) 설치하기
      run: npm ci
      
    - name: 테스트 실행하기
      run: npm test
